### ISSUE TITLE
Django's templates should not be shared

### ISSUE THREAD

**Issue by earthboundkid** [nicodv/django-uwsgi-nginx#1]
Django's template source files are intended to be kept secret and not shared with the public, but https://github.com/nicodv/django-uwsgi-nginx/blob/master/conf/nginx.conf#L21 exposes the templates with Nginx.

**Comment by nicodv** [comment]
Fixed by https://github.com/nicodv/django-uwsgi-nginx/commit/5e79cdf52bd63e15d770d6904ad59704784f8826
