### ISSUE TITLE
Static files should be shared from STATIC_ROOT, not project/static

### ISSUE THREAD

**Issue by earthboundkid** [nicodv/django-uwsgi-nginx#2]
In its intended behavior, every app in Django has its own /static/ directory with its own static files, which are then all combined into one directory (or server if you use S3 or similar) by the collectstatic management command. In this repo, only the /static/ of the main app is shared and STATIC_ROOT is not set. This also precludes post-processing via collectstatic, for example using [ManifestStaticFilesStorage](https://docs.djangoproject.com/en/1.9/ref/contrib/staticfiles/#manifeststaticfilesstorage) to automatically cache-bust files.

**Comment by nicodv** [comment]
Fixed. Thanks for reporting!
