### ISSUE TITLE
there is a error in this 

### ISSUE THREAD

**Issue by csfamily** [nicodv/django-uwsgi-nginx#3]
systemctl daemon-reload
service uwsgi restart

we can't restart the  uwsgi .

**Comment by nicodv** [comment]
You'll have to be more specific than that.

**Comment by csfamily** [comment]
oh，it seems that command “systemctl daemon-reload” is not useful for ubuntu14.04，is there any command can replace the “systemctl” ？

**Comment by nicodv** [comment]
This tutorial is for Debian, and has not been tested on Ubuntu. You might be able to do: `service uwsgi reload`.
